2020-05-22 16:35:01.053 [error] <0.1043.0> CRASH REPORT Process <0.1043.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"expected dispatch/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: :ok">>},[{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Endpoint',plug_builder_call,...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-22 16:35:01.057 [error] <0.1043.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.1042.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"expected dispatch/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: :ok">>},[{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Endpoint',plug_builder_call,...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 17:17:02.534 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 17:17:02.606 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 18:14:56.176 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 18:14:56.181 [error] <0.556.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.555.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 18:57:45.717 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 18:57:45.724 [error] <0.556.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.555.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 19:17:17.429 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 19:17:17.435 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 19:58:41.812 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 19:58:41.819 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,etimedout}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/plu..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 20:59:24.547 [error] <0.670.0> CRASH REPORT Process <0.670.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,unknown_host}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 20:59:24.550 [error] <0.670.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.669.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,unknown_host}},[{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,154}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/plug/router/utils.ex"},{line,109}]},{'Elixir.Matches.Endpoint',dispatch,2,[{file,"lib/..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:03:18.648 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,155}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:03:18.657 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,155}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:04:55.298 [error] <0.575.0> CRASH REPORT Process <0.575.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:04:55.301 [error] <0.575.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.574.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:06:38.008 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:06:38.015 [error] <0.668.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.667.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:07:46.023 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:07:46.030 [error] <0.668.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.667.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:10:28.994 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:10:29.002 [error] <0.668.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.667.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:11:55.258 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:11:55.265 [error] <0.668.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.667.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:15:43.731 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:15:43.747 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:18:28.261 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:18:28.276 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{error,unknown_host}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"l..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:19:24.696 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{ok,#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.576.0>}}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:19:24.716 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Channel'},[{'Elixir.AMQP.Channel',open,[{ok,#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.576.0>}}],[{file,"lib/amqp/channel.ex"},{line,15}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',2,[{file,"lib/match_api/router.ex"},{line,157}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:55:33.926 [error] <0.579.0> CRASH REPORT Process <0.579.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => body,message => nil,term => #{'__struct__' => 'Elixir.HTTPotion.ErrorResponse',message => <<"req_timedout">>}},[{'Elixir.Matches.Router','-do_match/4-fun-3-',2,[{file,"lib/match_api/router.ex"},{line,83}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/p..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 21:55:33.930 [error] <0.579.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.578.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => body,message => nil,term => #{'__struct__' => 'Elixir.HTTPotion.ErrorResponse',message => <<"req_timedout">>}},[{'Elixir.Matches.Router','-do_match/4-fun-3-',2,[{file,"lib/match_api/router.ex"},{line,83}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,2,[{file,"lib/match_api/router.ex"},{line,1}]},{'Elixir.Plug.Router.Utils',forward,4,[{file,"lib/p..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:24:59.572 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.MultipleResultsError',message => <<"expected at most one result but got 2 in query:\n\nfrom m in Matches.Match,\n  where: m.\"FirstProfileId\" == ^1 and m.\"SecondProfileId\" == ^2 or m.\"SecondProfileId\" == ^1 and m.\"FirstProfileId\" == ^2,\n  select: [m.\"MatchedContactId\", m.\"FirstProfileId\", m.\"SecondProfileId\"]\n">>},[{'Elixir.Ecto.Repo.Queryable',one,4,[{file,"lib/ecto/repo/queryable.ex"},{line,73}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:24:59.586 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.MultipleResultsError',message => <<"expected at most one result but got 2 in query:\n\nfrom m in Matches.Match,\n  where: m.\"FirstProfileId\" == ^1 and m.\"SecondProfileId\" == ^2 or m.\"SecondProfileId\" == ^1 and m.\"FirstProfileId\" == ^2,\n  select: [m.\"MatchedContactId\", m.\"FirstProfileId\", m.\"SecondProfileId\"]\n">>},[{'Elixir.Ecto.Repo.Queryable',one,4,[{file,"lib/ecto/repo/queryable.ex"},{line,73}]},{'Elixir.Matches.Router','-do_match/4-fun-5-',...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:52:50.451 [error] <0.592.0> CRASH REPORT Process <0.592.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead">>},[{'Elixir.Ecto.Query.Builder','not_nil!',1,[{file,"lib/ecto/query/builder.ex"},{line,551}]},{'Elixir.Matches.Router','-do_match/4-fun-1-',2,[{file,"lib/match_api/router.ex"},{line,32}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:52:50.462 [error] <0.592.0> Cowboy stream 1 with ranch listener 'Elixir.Matches.Endpoint.HTTP' and connection process <0.591.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead">>},[{'Elixir.Ecto.Query.Builder','not_nil!',1,[{file,"lib/ecto/query/builder.ex"},{line,551}]},{'Elixir.Matches.Router','-do_match/4-fun-1-',2,[{file,"lib/match_api/router.ex"},{line,32}]},{'Elixir.Matches.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Matches.Router',plug_builder_call,...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
